#!/bin/bash
function usage {
  cat <<EOF
battery usage:
  general:
    -h            print this message
    -t            output tmux status bar format
    -z            output zsh prompt format
    -i            enable nerd fonts battery indicators
    -p            use pmset (more accurate)
  colors:                                                 tmux     zsh
    -g <color>    good battery level      default: 1;32 | green  | 64
    -m <color>    middle battery level    default: 1;33 | yellow | 136
    -w <color>    warn battery level      default: 0;31 | red    | 160
EOF
}

if [[ $1 == '-h' ]]; then
  usage
  exit 0
fi

function set_defaults {
    charging=false
    color_template="%s"
    TMUX_COLOR_TEMPLATE="#[fg=%s]"
    ZSH_COLOR_TEMPLATE="%%F{%s}"
    pmset_on=0
    output_tmux=0
    output_zsh=0
    good_color="1;32"
    middle_color="1;33"
    warn_color="0;31"
    charge_icon='ϟ'
    show_battery_icon=false
}


# Determine battery charge state
function battery_charge {
  case $(uname -s) in
  "Darwin")
    if ((pmset_on)) && command -v pmset &>/dev/null; then
      [ "$(pmset -g batt | grep -o 'AC Power')" ] && charging=true
      BATT_PCT=$(pmset -g batt | grep -o '[0-9]*%' | tr -d %)
    else
      while read key value; do
        case $key in
        "MaxCapacity")
          maxcap=$value
          ;;
        "CurrentCapacity")
          curcap=$value
          ;;
        "ExternalConnected")
          [ $value == "Yes" ] && charging=true
          ;;
        esac
        if [[ -n "$maxcap" && -n $curcap ]]; then
          BATT_PCT=$((100 * curcap / maxcap))
        fi
      done < <(ioreg -n AppleSmartBattery -r | grep -o '"[^"]*" = [^ ]*' | sed -e 's/= //g' -e 's/"//g' | sort)
    fi
    ;;
  "Linux")
    battery_path=/sys/class/power_supply/BAT0
    case $(cat /etc/*-release) in
    *"Arch Linux"* | *"Ubuntu"*)
      battery_state=$(cat $battery_path/energy_now)
      battery_full=$battery_path/energy_full
      battery_current=$battery_path/energy_now
      ;;
    *)
      battery_state=$(cat $battery_path/status)
      battery_full=$battery_path/charge_full
      battery_current=$battery_path/charge_now
      ;;
    esac

    [ $battery_state == 'Charging' ] && charging=true
    now=$(cat $battery_current)
    full=$(cat $battery_full)
    BATT_PCT=$((100 * $now / $full))
    ;;
  esac
}

# Apply the correct color to the battery status prompt
function apply_colors {
  # Green
  if [[ $BATT_PCT -ge 75 ]]; then
    COLOR=$(printf "$color_template" "$good_color")

  # Yellow
  elif [[ $BATT_PCT -ge 25 ]] && [[ $BATT_PCT -lt 75 ]]; then
    COLOR=$(printf "$color_template" "$middle_color")

  # Red
  elif [[ $BATT_PCT -lt 25 ]]; then
    COLOR=$(printf "$color_template" "$warn_color")
  fi
}

# Apply the correct icon to the battery status prompt
function apply_battery_icon {
  if $charging; then
    GRAPH=${charge_icon}
  else
    if [[ $BATT_PCT -ge 95 ]]; then
      GRAPH=" "

    elif [[ $BATT_PCT -ge 75 ]] && [[ $BATT_PCT -lt 95 ]]; then
      GRAPH=" "

    elif [[ $BATT_PCT -ge 25 ]] && [[ $BATT_PCT -lt 75 ]]; then
      GRAPH=" "

    elif [[ $BATT_PCT -lt 25 ]]; then
      GRAPH=" "
    fi
  fi
}

# Print the battery status
function print_status {
  if [ show_battery_icon ] ; then
    apply_battery_icon
  else
    if $charging; then
      GRAPH=${charge_icon}
    fi
  fi

  if ((output_tmux)); then
    printf "%s%s %s%s" "$COLOR" "$BATT_PCT%" "$GRAPH" "#[default]"
  elif ((output_zsh)); then
    printf "%%B%s%s %s" "$COLOR" "$BATT_PCT%" "$GRAPH"
  else
    printf "\e[0;%sm%s %s \e[m\n" "$COLOR" "$BATT_PCT%" "$GRAPH"
  fi
}

set_defaults
# Read args
while getopts "g:m:w:tizp" opt; do
  case $opt in
  g)
    good_color=$OPTARG
    ;;
  m)
    middle_color=$OPTARG
    ;;
  w)
    warn_color=$OPTARG
    ;;
  i)
    show_battery_icon=true
    ;;
  t)
    color_template="$TMUX_COLOR_TEMPLATE"
    output_tmux=1
    good_color="balck"
    middle_color="yellow"
    warn_color="red"
    ;;
  z)
    color_template="$ZSH_COLOR_TEMPLATE"
    output_zsh=1
    good_color="64"
    middle_color="136"
    warn_color="160"
    ;;
  p)
    pmset_on=1
    ;;
  \?)
    echo "Invalid option: -$OPTARG"
    exit 1
    ;;
  esac
done

battery_charge
apply_colors
print_status
