#!/bin/bash

# A dmenu prompt to unmount drivers.
# Provides you with mounted partitions, select one to unmout.

# Drives mounte at /, /boot and /home will not be options to unmount.
# This can be changed by modifying $exclusionregex.

exclusionregex="\(/boot\|/home\|/\)$"
drives=$(lsblk -lp | grep "t /" | grep -v "$exclusionregex" | awk '{print $1, "(" $4 ")", "on", $7}')
[[ "$drives" = "" ]] && exit
chosen=$(echo "$drives" | dmenu -i -p "Unmount which drive?" | awk '{print $1}')
[[ "$chosen" = "" ]] && exit
# pgrep -x dnust kills the notification deamon that we use, in order to send the new notification.
# If you use another nofitication deamon you need to change this part
sudo umount $chosen && pgrep -x dunst && notify-send "dm_unmount" "$chosen unmounted."
