#!/usr/bin/env sh
source utils

if [ $(current_os) = 'macos' ]; then
    # The signal strength for a connection is the value for agrCtlRSSI. "RSSI" stands for received signal strength indication. The higher the number, the stronger the wireless signal. For Apple OS X systems, the value will range from a high of 0 down to minus 100 (-100). The closer the number is to zero, the stronger the signal while the closer the number is to negative 100, the weaker the signal strength.
    RSSI="$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk -F': ' '/ agrCtlRSSI/{print $2}')"
    WIFI_STRENGHT=($RSSI + 100)
    echo $WIFI_STRENGHT
else
    # Ethernet
    # e* indicates ethernet connection
    # if you want to indicate if a wifi is connected just change it to w*
    #     ,
    # For some reason I can't use the varialbe ethernet_path="/sys/class/net/e*"
    if [ -d /sys/class/net/e* ] && [ $(cat /sys/class/net/e*/operstate) = 'up' ]; then
        echo "Ethernet"
    else
        # Wifi quality percentage and up/down if connected
        #       
        grep "^\s*w" /proc/net/wireless | awk '{ print "", int($3 * 100 / 70) "%" }'
    fi
fi
