#!/bin/bash -
source utils

ROOT_GIT_DIR=$(git rev-parse --show-toplevel) || exit_w_error "Not a Git repository."
WORKTREE_DIR=${ROOT_GIT_DIR%/*} # parent directory of the current git top-level directory

SCRIPT_NAME=${0##*/}  # performed a string manipulation operation to get the script name

help()
{
    # here-document used instead of echoing all lines
   cat <<-HMESSAGE
Choose a Git worktree under "$WORKTREE_DIR" and print its path.

To change directories in your shell using this script, use:

    cd "\$($SCRIPT_NAME)"

Syntax: $SCRIPT_NAME [-h]

Options:
  -h       Show this help message and exit.
HMESSAGE
}

while getopts "h" option; do
    case $option in
        h )
            help
            exit 0;;
        \?)
            exit_w_error "Error: Invalid option";;
    esac
done
shift $((OPTIND -1)) # remove all options from $#

WORKTREES=$(gtree_ls) || exit 1

WORKTREES=$(gtree_ls | sed "s|$WORKTREE_DIR/||")
CHOOSEN=$(echo "$WORKTREES" | fzf --height "25%" --header "Choose the workingtree" --reverse --border | awk '{print $1}')
[ -n "$CHOOSEN" ] && echo "$WORKTREE_DIR/$CHOOSEN"
