#!/bin/bash
source utils

# terminal-notifier is a macos notifier pacakge, if you are on linux you can use
# notify-send
MUSIC_DIR="$HOME/my-music"

YT_DW=""
if is_installed 'youtube-dl'; then
    YT_DW='youtube-dl'
elif is_installed 'yt-dlp'; then
    YT_DW='yt-dlp'
else
    exit_w_error "Can' download, you have to install youtube-dl or yt-dlp"
fi

$YT_DW -x --audio-format mp3 --output "$MUSIC_DIR/%(title)s.%(ext)s" "$1"

if [ $? -eq 0 ]; then
    message='Finished downloading'
else
    message='Error downloading mp3'
fi

title='mp3-download'
if is_installed dunst; then
    # pgrep -x dunst kills the notification deamon that we use, in order to send the new notification.
    pgrep -x dunst && notify-send "$title" "$message"
elif is_installed terminal-notifier; then
    terminal-notifier -title "$title" -message "$message"
fi
