#!/bin/bash
source utils

# terminal-notifier is a macos notifier pacakge, if you are on linux you can use
# notify-send

is_installed 'youtube-dl' || exit_w_error 'youtube-dl is not installed'

youtube-dl -x --audio-format mp3 "$1"

if [ $? -eq 0 ]; then
    message='Finished downloading'
else
    message='Error downloading mp3'
fi

title='mp3-download'
if is_installed dunst; then
    # pgrep -x dunst kills the notification deamon that we use, in order to send the new notification.
    pgrep -x dunst && notify-send "$title" "$message"
elif is_installed terminal-notifier; then
    terminal-notifier -title "$title" -message "$message"
fi
