#!/bin/bash -
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
source "$SCRIPT_DIR/utils"

# Safety: Exit if a command fails
set -euo pipefail

SCRIPT_NAME=${0##*/}  # performed a string manipulation operation to get the script name
BASE_COMMAND_NAME='pkg'

subcommands=$(cat <<-SUB
Subcommands:
  checkupdates     List all packages that have available updates.
  install          Install a package via package manager
  install_from_dir Install a package from a directory
  remove           Remove/Uninstall a package via package manager
  upgrade          Upgrade all installed packages to their latest version.
SUB
)

function help {
cat <<-HMESSAGE
A wrapper script that abstracts package operations across different operating systems.

Syntax: $SCRIPT_NAME [-h] <subcommands> [options] [<argumenets>]

Options:
  -h               Show this help message and exit.

$subcommands

Description:
  This script simplifies package management by providing a unified interface
  for various operating systems, hiding the underlying command differences.
HMESSAGE
}
[[ $# -eq 0 ]] && { help; exit 0; }
SUBCOMMAND="$1"

if [[ "$SUBCOMMAND" == "-h" || "$SUBCOMMAND" == "--help" ]]; then
    help
    exit 0
fi

COMMAND_FILE="${SCRIPT_DIR}/${BASE_COMMAND_NAME}_${SUBCOMMAND}"
if [ ! -f "$COMMAND_FILE" ]; then
    log_error "Error: unknown subcommand '$SUBCOMMAND'. File '$COMMAND_FILE' not found."
    exit_w_error "$subcommands"
fi

shift # Remove the subcommand name from the argument list

bash "$COMMAND_FILE" "$@"
