#!/bin/bash -
source utils

SCRIPT_NAME=${0##*/}  # performed a string manipulation operation to get the script name
function help {
  cat <<EOF
Install a package:

Usage:
  $SCRIPT_NAME [-h] <pkg-name>

Options:
  -h     Print this help message and exit.

Arguments:
  <pkg-name>     Name of the package to install

Examples:
  $SCRIPT_NAME htop

EOF
}

while getopts "h" option; do
    case $option in
        h )
            help
            exit 0;;
        \?)
            exit_w_error "Error: Invalid option";;
    esac
done
shift $((OPTIND -1)) # remove all options from $#

case $(current_os) in
    "macos")
        os="MacOS"
        CMD="brew install"
        ;;
    "arch")
        os="Arch Linux"
        CMD="sudo pacman -S"
        ;;
    "ubuntu")
        os="Ubuntu Linux"
        CMD="sudo apt install"
        ;;
    "fedora")
        os="Fedora Linux"
        CMD="sudo dnf install"
        ;;
    *)
        exit_w_error "This OS is not handled yet."
        ;;
esac

PKG_NAME="$1"
if [[ -z "$PKG_NAME" ]]; then
    echo "Error: Missing the package name"
    help
    exit 1
fi

log_title "Identified OS: $os"
log_title "Executing: $CMD $PKG_NAME"
$CMD $PKG_NAME
