#!/bin/bash -
source utils

SCRIPT_NAME=${0##*/}  # performed a string manipulation operation to get the script name
function help {
  cat <<EOF
Install a package:

Usage:
  $SCRIPT_NAME [-h] <pkg-name>

Options:
  -h     Print this help message and exit.

Arguments:
  <pkg-name>     Name of the package to install

Examples:
  $SCRIPT_NAME htop

EOF
}

while getopts "h" option; do
    case $option in
        h ) help; exit 0;;
        \?) exit_w_error "Error: Invalid option";;
    esac
done
shift $((OPTIND -1)) # remove all options from $#

case $(current_os) in
    "macos")
        os="MacOS"
        # Homebrew usually auto-updates, but we can force it
        UPDATE_CMD="brew update"
        INSTALL_CMD="brew install"
        ;;
    "arch")
        os="Arch Linux"
        UPDATE_CMD="sudo pacman -Sy"
        INSTALL_CMD="sudo pacman -S"
        ;;
    "ubuntu")
        os="Ubuntu Linux"
        UPDATE_CMD="sudo apt-get update"
        INSTALL_CMD="sudo apt install"
        ;;
    "fedora")
        os="Fedora Linux"
        # DNF does this automatically with metadata timers,
        # but we can force a check if we want to be safe.
        UPDATE_CMD="true"
        INSTALL_CMD="sudo dnf install"
        ;;
    *)
        exit_w_error "This OS is not handled yet."
        ;;
esac

# Store all arguments as the package list
PKG_LIST="$*"
if [[ -z "$PKG_LIST" ]]; then
    log_error "Error: Missing the package name"
    help
    exit 1
fi

log_title "Identified OS: $os"
log_info "Refreshing package databases: $UPDATE_CMD"
$UPDATE_CMD
log_title "Installing the packages: $INSTALL_CMD $PKG_NAME"
$INSTALL_CMD "$PKG_LIST"
