#!/bin/bash -
source utils

SCRIPT_NAME=${0##*/}

function help {
   cat <<-HMESSAGE
Install a standalone Linux package to /opt and symlink to /usr/local/bin.

Usage:
  sudo $SCRIPT_NAME [-h] <src-directory> <executable-path>

Description:
  The package will be copied to /opt, and a symlink to the specified command will be
  created in /usr/local/bin (which is in your PATH).

Options:
  -h     Print this help message and exit.

Arguments:
  <src-directory>   The local folder containing the app (e.g., 'zen-browser')
  <executable-path> The path to the binary INSIDE that folder (e.g., 'zen' or 'bin/app')

Examples:
  sudo $SCRIPT_NAME zen-browser zen
  sudo $SCRIPT_NAME myapp/ bin/myapp

After installation, you can run the command directly from anywhere:
  zen

HMESSAGE
}

[[ $(current_os) == "macos" ]] && exit_w_error "This script is for Linux only."
[[ $(current_os) == 'wsl' ]] && exit_w_error "The script can't be run on a Windows OS"
[[ $# -lt 2 ]] && { help; exit 1; }

while getopts "h" option; do
    case $option in
        h ) help; exit 0 ;;
        \?) exit_w_error "Error: Invalid option" ;;
    esac
done

SRC_DIR="${1%/}"        # Strip trailing slash
REL_EXEC_PATH="$2"      # e.g., "bin/zen"
DIR_NAME=$(basename "$SRC_DIR") # e.g., "zen-pkg"
BIN_NAME=$(basename "$REL_EXEC_PATH") # e.g., "zen"
INSTALL_PATH="/opt/$DIR_NAME"
LINK_PATH="/usr/local/bin/$BIN_NAME"

log_title "Installing $DIR_NAME to /opt"
sudo cp -rv "$SRC_DIR" "/opt/"

# Create the symlink
# -s: symbolic, -f: force (overwrite old links), -v: verbose
log_info "Creating symlink: $INSTALL_PATH/$REL_EXEC_PATH -> $LINK_PATH"
sudo ln -sfv "$INSTALL_PATH/$REL_EXEC_PATH" "$LINK_PATH"

log_info "Done! You can now run '$BIN_NAME' from your terminal."
