#!/bin/bash -
source utils

SCRIPT_NAME=${0##*/}  # performed a string manipulation operation to get the script name
function help {
  cat <<EOF
Update all the packages:

Syntax: $SCRIPT_NAME [-h]
Options:
    -h            print this message
EOF
}

while getopts "h" option; do
    case $option in
        h )
            help
            exit 0;;
        \?)
            exit_w_error "Error: Invalid option";;
    esac
done
shift $((OPTIND -1)) # remove all options from $#

case $(current_os) in
    "macos")
        os="MacOS"
        CMD="brew upgrade"
        ;;
    "arch")
        os="Arch Linux"
        CMD="sudo pacman -Syu"
        ;;
    "ubuntu")
        os="Ubuntu Linux"
        CMD="sudo apt upgrade"
        ;;
    "fedora")
        os="Fedora Linux"
        CMD="sudo dnf upgrade --refresh"
        ;;
    *)
        exit_w_error "This OS is not handled yet."
        ;;
esac

log_title "Identified OS: $os"
log_title "Executing: $CMD"
$CMD
