#!/bin/bash -
source utils

SCRIPT_NAME=${0##*/}  # performed a string manipulation operation to get the script name
function help {
  cat <<EOF
Get the number of packages that can be updated:

Syntax: $SCRIPT_NAME [-h]
Options:
    -h            print this message
    -i            Add icons to the output
EOF
}

ICON=""
while getopts "hi" option; do
    case $option in
        h )
            help
            exit 0;;
        i )
            #   
            ICON="󰏔 "
            ;;
        \?)
            exit_w_error "Error: Invalid option";;
    esac
done
shift $((OPTIND -1)) # remove all options from $#

case $(uname -s) in
    "Darwin")
      CMD="brew outdated -q 2>/dev/null | wc -l"
    ;;
    "Linux")
        case $(cat /etc/*-release) in
            *"arch"*)
                CMD="checkupdates 2>/dev/null | wc -l"
                ;;
            *"Ubuntu"*)
                CMD="apt list --upgradable 2>/dev/null | grep upgradable | wc -l"
                ;;
            *"fedora"*)
                CMD="dnf check-update 2>/dev/null | grep -E '^\S' | wc -l"
                ;;
            *)
                exit_w_error "This OS is not handled yet."
                ;;
        esac
esac

log_title "Executing: $CMD"
n_packages=$(eval "$CMD")
echo $ICON $n_packages
