#!/bin/bash -
source utils

SCRIPT_NAME=${0##*/}  # performed a string manipulation operation to get the script name
function help {
  cat <<EOF
Get the number of packages that can be updated:

Syntax: $SCRIPT_NAME [-h]
Options:
    -h            print this message
    -i            Add icons to the output
    -q            Only print the number of packages an icon (if selected)
EOF
}

ICON=""
LOG='log_info'
while getopts "hiq" option; do
    case $option in
        h )
            help
            exit 0;;
        i )
            #   
            ICON="󰏔 "
            ;;
        q )
            LOG=':' # no-op, do nothing command
            ;;
        \?)
            exit_w_error "Error: Invalid option";;
    esac
done
shift $((OPTIND -1)) # remove all options from $#

case $(current_os) in
    "macos")
        os='MacOS'
        CMD="brew outdated -q 2>/dev/null | wc -l"
        ;;
    "arch")
        os='Arch Linux'
        CMD="checkupdates 2>/dev/null | wc -l"
        ;;
    "Ubuntu")
        os='Ubuntu Linux'
        CMD="apt list --upgradable 2>/dev/null | grep upgradable | wc -l"
        ;;
    "fedora")
        os='Fedora Linux'
        CMD="dnf check-update 2>/dev/null | grep -E '^\S' | wc -l"
        ;;
    *)
        exit_w_error "This OS is not handled yet."
        ;;
esac

$LOG "Identified OS: $os"
$LOG "Executing: $CMD"
n_packages=$(eval "$CMD")
echo $ICON $n_packages
