#!/bin/bash
SCRIPT_NAME=${0##*/}

function usage {
  cat <<EOF
Remove the duplicated lines from a file:
Syntax: $SCRIPT_NAME [-h] filename
Options:
    -h            print this message
EOF
}

if [[ $1 == '-h' ]]; then
  usage
  exit 0
fi

# for more details https://unix.stackexchange.com/questions/159695/how-does-awk-a0-work
awk '!seen[$0]++' $1
