#!/bin/bash
SCRIPT_NAME=${0##*/}

function usage {
  cat <<EOF
Remove the duplicated lines from a file without chainging the order of the lines:
Syntax: $SCRIPT_NAME [-h] filename
Options:
    -h            print this message
    -k            key to use to identify if a line is a duplicated line (by default we use the entire line $0)
                  If you want to check only the first and second values of the line write  `-k $1$2`
                      >>>>Still in TODO<<<<
EOF
}

if [[ $1 == '-h' ]]; then
  usage
  exit 0
fi

# for more details https://opensource.com/article/19/10/remove-duplicate-lines-files-awk
awk '!seen[$0]++' $1
