#!/bin/bash
SCRIPT_NAME=${0##*/}

function help {
  cat <<EOF
Remove the duplicated lines from a file without chainging the order of the lines:
Syntax: $SCRIPT_NAME [-h] filename
Options:
    -h            print this message
EOF
}

ID='0'
while getopts "h" option; do
    case $option in
        h )
            help
            exit 0;;
        \?)
            echo "Error: Invalid option"
            exit 1;;
    esac
done
shift $((OPTIND -1)) # remove all options from $#

# for more details https://klaudjanpepaj.com/posts/awk_the_unchained/#remove-duplicated-lines-without-changing-the-order-of-the-lines
awk '!seen[$0]++' $1
