#!/bin/bash

function help(){
    echo "Switch to a git branch, if the name of the branch is not specified search it using fzf"
    echo "Usage: $0 [-h] [branch]"
    echo "Options:"
    echo "    -h help"
}
while getopts "h" option; do
    case "$option" in
        h) help && exit 0;;
        *) help && exit 1;;
    esac
done

if [ $1 ]; then
    git checkout $1
    exit $?
else
    choosen_full_name=$(git branch -a | fzf)
    # remove `remotes/origin/` if the branch is not in the local machine, otherwise git will
    # switch to the `remotes/origin/branch_name` in detached mode, but we want to create a local branch that points to the remote
    choosen_branch_name=$(echo $choosen_full_name | sed 's/remotes\/origin\///')
    git checkout $choosen_branch_name
fi
