#!/bin/bash
set -o pipefail

SCRIPT_NAME=${0##*/}

function help {
   cat <<-HMESSAGE
Take a screenshot of a selected region, save it in /tmp,
and copy it to the clipboard.

Usage:
  $SCRIPT_NAME [-hgk]

Options:
  -h    Show this help message and exit.
  -g    Open the screenshot with GIMP.
  -k    Open the screenshot with ksnip.
HMESSAGE
}

OPEN_GIMP=false
OPEN_KSNIP=false
while getopts "hgk" option; do
    case $option in
        h ) help; exit 0;;
        g ) OPEN_GIMP=true;;
        k ) OPEN_KSNIP=true;;
        \?)
            echo "Error: Invalid option"
            exit 1;;
    esac
done

file="/tmp/screenshot-$(date +%Y%m%d-%H%M%S).png"

maim -s | tee "$file" | xclip -selection clipboard -t image/png -i

if [ $? -eq 0 ]; then
    notify-send -i "$file" "Screenshot" "Saved to $file and copied to clipboard"
    if $OPEN_GIMP; then
        gimp "$file"
    fi
    if $OPEN_KSNIP; then
        ksnip "$file"
    fi
fi
