#!/bin/bash
source "utils"

DELIM='|'

weather_status=$(timeout 5s weather -s || echo 'weather script is taking too long')
volume_status=$(vc -i)
battery_status=$(battery -i)
wifi_status=$(wifi -i)
pkg_status=$(updatable-pkg -i)
datetime=$(date "+%d %b %Y (%a) %H:%M")

echo "$weather_status$DELIM$volume_status$DELIM$battery_status$DELIM$wifi_status$DELIM$pkg_status$DELIM$datetime"
