#!/bin/bash -
source utils

SCRIPT_NAME=${0##*/}  # performed a string manipulation operation to get the script name
function help {
  cat <<EOF
Update all the packages:

Syntax: $SCRIPT_NAME [-h]
Options:
    -h            print this message
EOF
}

while getopts "h" option; do
    case $option in
        h )
            help
            exit 0;;
        \?)
            exit_w_error "Error: Invalid option";;
    esac
done
shift $((OPTIND -1)) # remove all options from $#

case $(uname -s) in
    "Darwin")
      brew update
    ;;
    "Linux")
        case $(cat /etc/*-release) in
            *"arch"*)
                pacman -Syu
                ;;
            *"Ubuntu"*)
                apt upgrade
                ;;
            *)
                echo "To implement"
                exit 1
                ;;
        esac
esac
