#!/bin/bash -
source utils

SCRIPT_NAME=${0##*/}  # performed a string manipulation operation to get the script name
function help {
  cat <<EOF
Update all the packages:

Syntax: $SCRIPT_NAME [-h]
Options:
    -h            print this message
EOF
}

while getopts "h" option; do
    case $option in
        h )
            help
            exit 0;;
        \?)
            exit_w_error "Error: Invalid option";;
    esac
done
shift $((OPTIND -1)) # remove all options from $#

case $(current_os) in
    "macos")
        CMD="brew upgrade"
        ;;
    *"arch"*)
        CMD="sudo pacman -Syu"
        ;;
    *"Ubuntu"*)
        CMD="sudo apt upgrade"
        ;;
    *"fedora"*)
        CMD="sudo dnf upgrade --refresh"
        ;;
    *)
        exit_w_error "This OS is not handled yet."
        ;;
esac

log_title "Executing: $CMD"
$CMD
