#!/usr/bin/env bash

export RED="\033[1;31m"
export YELLOW="\033[1;33m"
export NC="\033[0m" # No Color

log_info (){
    printf "${YELLOW}$1${NC}\n"
}
log_error (){
    printf "${RED}$1${NC}\n"
}
exit_with_error (){
    log_error "$1" && exit 1
}
