#!/bin/bash -
source utils
SCRIPT_NAME=${0##*/}
DEFAULT_NUM=5

function help {
   cat <<-HMESSAGE
[V]olume [C]ontrol
Use this command to raise/lower/mute/unmute your volume

Syntax: $SCRIPT_NAME [-hv] <command>
Options:
    -h     Print this help and exit.
    -v     Make more verbose the messages

Commands:
    up <num>    Rase the volume of <num> value, if passed, otherwise $DEFAULT_NUM
    down <num>  Lower the volume of <num> value, if passed, otherwise $DEFAULT_NUM
    mute   Mute
    toggle Mute/Unmute
HMESSAGE
}
DEBUG=':' # no-op, do nothing command


# -: is used to enable long arguments
while getopts "hv" option; do
    case $option in
        h )
            help
            exit 0;;
        v )
            DEBUG='echo';;
        \?)
            exit_w_error "Error: Invalid option";;
    esac
done
shift $((OPTIND -1)) # remove all options from $#

COMAND=$1
NUM="${2:-$DEFAULT_NUM}"
OPERATNG_SYSTEM=$(uname -s)
if [ $OPERATNG_SYSTEM = 'Darwin' ]; then # macos
        $DEBUG "Using osascript"

        function get_volume { osascript -e 'output volume of (get volume settings)' ;}
        function up { osascript -e "set volume output volume $(get_volume)+$NUM" ;}
        function down { osascript -e "set volume output volume $(get_volume)-$NUM" ;}
        function mute { osascript -e "set volume with output muted" ;}
        function unmute { osascript -e "set volume without output muted" ;}
        function is_muted { osascript -e "output muted of (get volume settings)" ;}
        function toggle {
            if $(is_muted); then
                unmute;
            else
                mute;
            fi
        }
else
    if is_installed pulsemixer; then
        $DEBUG "Using pulseaudio"
        function get_volume { pulsemixer --get-volume | awk '{print int($1 * 100/150)"%"}' ;}
        function up { pulsemixer --change-volume +"$NUM" ;}
        function down { pulsemixer --change-volume -"$NUM" ;}
        function mute { pulsemixer --mute ;}
        function is_muted { pulsemixer --get-mute ;}
        function toggle { pulsemixer --toggle-mute ;}
    elif is_installed amixer; then
        $DEBUG "Using amixer"
        function get_volume { log_error "Function not jet implemented" ;}
        function up { amixer sset Master "$NUM"%+ ; }
        function down { amixer sset Master "$NUM"%- ;}
        function mute { amixer sset Master mute ; }
        function is_muted { log_error "Function not jet implemented" ;}
        function toggle { amixer sset Master toggle ;}
    else
        exit_w_error "The script needs at least pulsemixer or amixer to work"
    fi
fi

case "$COMAND" in
    toggle) toggle ;;
    mute) mute ;;
    up) up ;;
    down) down ;;
    *) notify-send "No command executed" -u critical -t 5000; exit 1 ;;
esac

if [ $(is_muted) = 1 ]; then
    volume="Mute"
else
    volume=$(get_volume)
fi


if is_installed dunst; then
    dunstify -a "volume_control" -u low -r 9090 -h int:value:"$volume" -i "volume-$COMAND" "Volume: $volume" -t 2000
elif is_installed terminal-notifier; then
    title='volume control'
    message="Volume: $volume"
    # terminal-notifier is a macos notifier pacakge, if you are on linux you can use
    # pgrep -x dunst kills the notification deamon that we use, in order to send the new notification.
    pgrep -x terminal-notifier # does not work
    terminal-notifier -title "$title" -message "$message"
fi


# update the statusbar, it expect to have 'statubar' script in your PATH
# update the signal of statusbar
# pkill -RTMIN+10 statusbar
