#!/bin/bash -
source utils

if ! is_installed xinput; then
    log_info "Installing xinput"
    sudo dnf install -y xinput
fi
if ! is_installed xsetwacom; then
    log_info "Installing xorg-x11-drv-wacom"
    sudo dnf install -y xorg-x11-drv-wacom
fi

INPUT_DEVICES=$(xinput)
# The name of the device might changes from computer to computer
PEN_DEVICE_NAME="Wacom Intuos BT S Pen Pen (0x12810659)"
log_info "Searching for device name $PEN_DEVICE_NAME"
[[ "$INPUT_DEVICES" != *"$PEN_DEVICE_NAME"* ]] && exit_w_error "Device not found. The name migh have change, run 'xinput' and search for it"

# Map Wacom pet to the main monitor
MONITOR="DP-2"
xinput map-to-output "$PEN_DEVICE_NAME" $MONITOR
log_info "Wacom mapped to monitor $MONITOR"


if hash nvim 2> /dev/null ; then
    log_title "Changing pressure..."
    CURRENT_PRESSURE=$(xsetwacom --get "$PEN_DEVICE_NAME" PressureCurve)
    log_info "The current pressure is: $CURRENT_PRESSURE"

    # make the pen send maximum pressure all the time
    xsetwacom --set "$PEN_DEVICE_NAME" PressureCurve 0 100 0 100

    NEW_PRESSURE=$(xsetwacom --get "$PEN_DEVICE_NAME" PressureCurve)
    log_info "The new pressure is: $NEW_PRESSURE"
    log_info "Now the pen sends the maximum pressure all the time, like a mouse"

    log_title "Setting Express keys..."
    # keyshortcut for GIMP usage
    PAD_DEVICE_NAME="Wacom Intuos BT S Pad pad"
    xsetwacom set "$PAD_DEVICE_NAME" Button 1 "key ctrl n" # create new image
    log_info "Express key 1 mapped to: crt+n (GIMP create new image)"
    xsetwacom set "$PAD_DEVICE_NAME" Button 2 "key shift ctrl n" # create new layer
    log_info "Express key 2 mapped to: shift+crt+n (GIMP create new layer)"
    xsetwacom set "$PAD_DEVICE_NAME" Button 3 "key f2" # open "color dialog", this is a custom shortuct setted by me on GIMP
    log_info "Express key 3 mapped to: f2 (GIMP open color dialog)"
    xsetwacom set "$PAD_DEVICE_NAME" Button 8 "key shift ctrl h" # "Hide docks" (toggle tools windows), this is a custom shortuct setted by me on GIMP
    log_info "Express key 8 mapped to: shift+crt+h (GIMP toggle tools windows)"

else
    log_error "xsetwacom is not installed"
fi


