#!/bin/bash -
source utils

PEN_DEVICE_NAME="Wacom Intuos BT S Pen stylus"

# Map Wacom pet to the main monitor
MONITOR="DP-2"
xinput map-to-output "$PEN_DEVICE_NAME" $MONITOR
log_info "Wacom mapped to monitor $MONITOR"


if hash nvim 2> /dev/null ; then
    log_title "Changing pressure..."
    CURRENT_PRESSURE=$(xsetwacom --get "$PEN_DEVICE_NAME" PressureCurve)
    log_info "The current pressure is: $CURRENT_PRESSURE"

    # make the pen send maximum pressure all the time
    xsetwacom --set "$PEN_DEVICE_NAME" PressureCurve 0 100 0 100

    NEW_PRESSURE=$(xsetwacom --get "$PEN_DEVICE_NAME" PressureCurve)
    log_info "The new pressure is: $NEW_PRESSURE"
    log_info "Now the pen sends the maximum pressure all the time, like a mouse"

    log_title "Setting Express keys..."
    # keyshortcut for GIMP usage
    PAD_DEVICE_NAME="Wacom Intuos BT S Pad pad"
    xsetwacom set "$PAD_DEVICE_NAME" Button 2 "key f2" # open "color dialog", this is a custom shortuct setted on GIMP
    log_info "Express key 2 mapped to: f2"
    xsetwacom set "$PAD_DEVICE_NAME" Button 3 "key shift ctrl n" # create new layer
    log_info "Express key 3 mapped to: shift+crt+n"
    xsetwacom set "$PAD_DEVICE_NAME" Button 8 "key shift ctrl h" # toggle tools windows
    log_info "Express key 8 mapped to: shift+crt+h"

else
    log_error "xsetwacom is not installed"
fi


