#!/usr/bin/env bash
source utils

function help {
   cat <<-HMESSAGE
Get the weater of your IP location, or the specified location

Syntax: $SCRIPT_NAME [-hs] [location]
Options:
    -h     Print this help and exit.
    -s     Return the current weather in a single string format
HMESSAGE
}

# show current weather
FORMAT='-0qm'
while getopts "hs" option; do
    case $option in
        h )
            help
            exit 0;;
        s )
            FORMAT="format=%c+%t+%h+%w+%m";;
        \?)
            echo "Error: Invalid option"
            exit 1;;
    esac
done
shift $((OPTIND -1)) # remove all options from $#

LOCATION="$1"
is_installed CoreLocationCLI && LOCATION="${1:-$(CoreLocationCLI --json | jq -r '.locality' 2>/dev/null)}"
curl -fGsS --compressed "wttr.in/${LOCATION}"?"m&lang=en&${FORMAT}"
