#!/usr/bin/env sh

ON_ICON="ON"
OFF_ICON="OFF"

WIFI_NAME="$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk -F': ' '/ SSID/{print $2}')"

[ "$WIFI_NAME" = "" ] && printf "%s" "$OFF_ICON" || printf "%s" "$ON_ICON $WIFI_NAME"
