#!/bin/bash -

## Settings
xsetroot -cursor_name left_ptr & # set the cursor to be a arrow and not an X
setxkbmap -option caps:escape # remap caps lock to escape
# xset -r # key holding will print only one character

# prevent monitor to turn off
xset -dpms
xset s noblank
xset s off

# Add wallpaper
xwallpaper --zoom ~/.config/wallpaper.png
